n_steps: 1200
n_epochs: 300
learning_rate: 0.0001
n_gpus: 1

beta_scheduler_params:
  beta_schedule: 'warmup10'
  start: 0.00001
  end: 0.01

checkpoint_params:
  dirpath: ''
  filename: ddpm_{epoch:02d}_{train_loss:04f}
  every_n_epochs: 50
  save_last: true
  save_top_k: -1

dataset_params:
  data_path: ''
  filename: 'photons_XYTE_E5.6_s0.0_a1.5.npy'
  batch_size: 10000

logger:
  save_dir: ''
  name: 'warmup10'
  flush_logs_every_n_steps: 1000